### ISSUE TITLE
SIA: Support for hierarchical image directory

### ISSUE THREAD

**Issue by Avni-Hirpara** [l3p-cv/lost#111]
**Is your feature request related to a problem? Please describe.**
As we will be mounting image path, Sometimes images are not directly available on the mounted repository but it has child directories to refer to. Also it might have other files(not images) which will crash application at annotation level. Can we extend application to support that feature?

**Describe alternatives you've considered**
 For me it is mandatory business requirement.
 I can contribute.

**Comment by jaeger-j** [comment]
Hi @Avni-Hirpara,
thank you for your feature request.
In order to contribute please follow our [contribution guide](https://lost.readthedocs.io/en/1.3/contribution_guide.html#how-to-contribute-new-features-or-bug-fixes)

A good starting point would be to copy this [request_annos script](https://github.com/l3p-cv/lost/blob/master/backend/lost/pyapi/examples/pipes/no_ai/request_annos.py) and to adjust it, in oder to deal with child directories. After that you can copy the [no_ai.sia_all_tools pipeline](https://github.com/l3p-cv/lost/blob/master/backend/lost/pyapi/examples/pipes/no_ai/sia_all_tools.json) and insert your version of the request_annos script. 
All information about pipeline development can be found [here](https://lost.readthedocs.io/en/1.3/all_about_pipelines.html) and [here](https://lost.readthedocs.io/en/1.3/all_about_scripts.html).

Best,
Jonas

**Comment by Avni-Hirpara** [comment]
@jaeger-j - Please refer pull request - https://github.com/l3p-cv/lost/pull/112
