### ISSUE TITLE
SIA: Exception PipeElementID = 59

### ISSUE THREAD

**Issue by josebenitezg** [l3p-cv/lost#129]
I have several SIA pipelines working and 2 of them show me this error

```
Traceback (most recent call last): File "/code/backend/lost/logic/pipeline/cron.py", line 346, 
in celery_exec_script raise Exception(err.decode('utf-8')) Exception PipeElementID = 59

```

**OS info:**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by gereonreus** [comment]
Hi @josebenitezg 

Sorry for that late reply !
After a period of inactivity in this repo we made it to our goal to develop the new LOST 2.x version.

If your issue is still relevant for you, please reopen this issue and give us [more information](https://github.com/l3p-cv/lost/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
