### ISSUE TITLE
Can't add a new class as the pipeline has defined

### ISSUE THREAD

**Issue by Shuai-Xie** [l3p-cv/lost#40]
In my annotation case, the new class objects will appear frequently.

In Dataturks, I can go to the backend of the Dataset Project and add the new class. But in LOST, I can't find this feature, so that I have to define a new pipeline. This wastes a lot of time.

**Comment by jaeger-j** [comment]
Please perform the following steps in order to add class labels when new classes appear during an annotation task:
1.  Switch to the designer view (Click on **designer** at the top right in the web GUI)
2.  Navigate to the labels site (Click on the **Labels** button on the left)
3. Select your label tree in the table
4. Click on the node where you want to add the child label
5. Type the label **name** and **description** into the input fields (see image below for an example)
6. Go back to the annotation view and perform the annotation task (Please note that you may need to refresh the site in order to load the new labels)

![add-new-label](https://user-images.githubusercontent.com/37367934/67156714-a8ec3200-f322-11e9-8c06-31b2a2c0868b.png)

**Comment by Shuai-Xie** [comment]
Thanks, @jaeger-j  Maybe I need to refresh the site and have a new try.

**Comment by Shuai-Xie** [comment]
Hi, @jaeger-j  I've tried what you suggested. Very helpful! 

At first, I thought the labels for a pipeline can't be updated as we couldn't edit the pipeline again.

Now I know I am wrong! **LabelTree can update its children labels. As long as I choose all the father nodes in a LabelTree, I can add any father and child nodes at any time!  That's indeed what I want!**

In your docs, I read that the LabelTree can be imported from a CSV file. **But I don't know how to export an expanding LabelTree edited in the `Designer->Labels` page.**

Thanks a lot.

**Comment by jaeger-j** [comment]
Hi, @Shuai-Xie 
> In your docs, I read that the LabelTree can be imported from a CSV file. But I don't know how to export an expanding LabelTree edited in the Designer->Labels page.

In the current version of LOST you can only export a label tree via the command line interface inside the docker container: https://lost.readthedocs.io/en/latest/lost_cli.html#export-label-tree
