### ISSUE TITLE
LabelTree is not a Real Tree in annotation CSV file!

### ISSUE THREAD

**Issue by Shuai-Xie** [l3p-cv/lost#42]
In my opinion, LabelTree helps to find a class by its superclass. 

However, in LOST, **you can just choose one between the class and its superclass**. I think the exported CSV should contain all the node classes from the root node to the leaf node. In this way, the CSV file can be more rational and sufficient to parse.

**Comment by jaeger-j** [comment]
## Export a label tree from LOST CLI
In order to export a whole label tree, you can use the lost command line interface: https://lost.readthedocs.io/en/latest/lost_cli.html#export-label-tree

## Export a label tree in a script
If you like to work with LOST label trees from a script you can use the LabelTree object: https://lost.readthedocs.io/en/latest/pyapi.html#labeltree
Here is a code snippet that you can use in a [script](https://lost.readthedocs.io/en/latest/all_about_scripts.html#all-about-scripts):
```
from lost.logic.label import LabelTree

...

tree = LabelTree(self._dbm, name='LabelTreeName')
df = tree.to_df()
csv_path = self.get_path('label_tree.csv', context='instance')
df.to_csv(csv_path, index=False)
```
