### ISSUE TITLE
Only rectangle annotation is available! 

### ISSUE THREAD

**Issue by ShroukMansour** [l3p-cv/lost#43]
I Only ably to find rectangle annotation, no polygon, line or point are there 

and I've followed the setup instructions as described in the readme.

Here is a screenshot 
![Screenshot from 2019-10-20 10-26-04](https://user-images.githubusercontent.com/18499889/67156896-ad194f00-f324-11e9-9db3-0b71c8706a28.png)

**Desktop:**
 - OS: [Ubuntu 16.04]
 - Browser [Mozzila firefox]
 - Version [69.0.2 (64-bit)]

**Comment by jaeger-j** [comment]
Hi @ShroukMansour,

I guess you started the **sia.semiauto_yolov3**. This pipeline is configured to allow only box annotations. 
You can start the **sia.sia_all_tools** pipeline in order to use all the tools you expected.

Please note also, that you are using LOST version 0.x.x. 
LOST version 1.0.0 was released a few days ago. If you just started to use LOST you should use the new version. In order to do that, you can pull the master branch and perform the quick_setup again.

**Comment by ShroukMansour** [comment]
@jaeger-j I just 've discovered that in the current moment. I will start using the new version, what are the new features?

**Comment by ShroukMansour** [comment]
@jaeger-j  and, can I use LOST for segmentation tasks?

**Comment by jaeger-j** [comment]
Hi @ShroukMansour,
the main new feature is, that SIA was rewritten in react. SIA now supports a fullscreen mode and allows to assign multiple labels to an annotation or the whole image. For a detailed description of the new features please have a look at the Changelog: https://github.com/l3p-cv/lost/blob/master/CHANGELOG.md#100-alpha0---2019-10-01

**Comment by jaeger-j** [comment]
> can I use LOST for segmentation tasks?

Yes, you can use the polygon tool in the [SIA](https://lost.readthedocs.io/en/latest/annotators.html#getting-to-know-sia-a-single-image-annotation-tool) interface.

We already used LOST to build a pipeline for semi-automatic seagrass segmentation in a student project: https://github.com/EnviewFulda/LookingForSeagrassLostPipeline
In order to generate annotation proposals we used DeepLabv3Plus as proposed in this work: https://ieeexplore.ieee.org/document/8867064
