### ISSUE TITLE
Support hierarchical labels

### ISSUE THREAD

**Issue by fran6co** [l3p-cv/lost#69]
**Describe the bug**
When using hierarchical labels in annotations SIA will fail to render

**To Reproduce**
1. Use labels with more than one level
```
idx,name,abbreviation,description,timestamp,external_id,is_deleted,parent_leaf_id,is_root
1,Pizzas,,Pizza dataset,,,,,True
2,pizza,,Pizza,,1,,1,
3,pizza_chorizo,,Pizza chorizo,,2,,2,
4,pizza_margherita,,Pizza margherita,,3,,2,
```
2. Feed already labeled data that use the children labels (e.g.: pizza_chorizo)
3. Go to SIA

**Expected behavior**
Be able to select any of the labels, regardless how deep they are. (e.g.: pizza, pizza_chorizo, pizza_margherita)

**Screenshots**
![image](https://user-images.githubusercontent.com/726088/78803815-bcb64e00-79bf-11ea-95fd-9eaf2427d4a3.png)

```
ANNOTATION: annoChangeMode - Render Single Anno state Object
Annotation.js:239 Annotation getLabel before Array(1)
ToolBar.js:407 Toobar state Object Object
react-dom.production.min.js:4636 TypeError: Cannot read property 'color' of undefined
    at Annotation.getColor (Annotation.js:240)
    at Annotation.getStyle (Annotation.js:248)
    at Annotation.renderAnno (Annotation.js:296)
    at Annotation.render (Annotation.js:353)
    at vi (react-dom.production.min.js:4241)
    at ui (react-dom.production.min.js:4232)
    at gk (react-dom.production.min.js:6671)
    at fk (react-dom.production.min.js:5648)
    at Zj (react-dom.production.min.js:5637)
    at Lj (react-dom.production.min.js:5393)
Pi @ react-dom.production.min.js:4636
n.callback @ react-dom.production.min.js:5081
Lg @ react-dom.production.min.js:3059
Kg @ react-dom.production.min.js:3047
ik @ react-dom.production.min.js:6342
n.unstable_runWithPriority @ scheduler.production.min.js:266
fg @ react-dom.production.min.js:2794
Yj @ react-dom.production.min.js:6105
Lj @ react-dom.production.min.js:5408
(anonymous) @ react-dom.production.min.js:2829
n.unstable_runWithPriority @ scheduler.production.min.js:266
fg @ react-dom.production.min.js:2794
ig @ react-dom.production.min.js:2824
jg @ react-dom.production.min.js:2814
hb @ react-dom.production.min.js:7205
Qd @ react-dom.production.min.js:1741
Hc @ react-dom.production.min.js:1778
Pd @ react-dom.production.min.js:1753
react-dom.production.min.js:2835 Uncaught TypeError: Cannot read property 'color' of undefined
    at Annotation.getColor (Annotation.js:240)
    at Annotation.getStyle (Annotation.js:248)
    at Annotation.renderAnno (Annotation.js:296)
    at Annotation.render (Annotation.js:353)
    at vi (react-dom.production.min.js:4241)
    at ui (react-dom.production.min.js:4232)
    at gk (react-dom.production.min.js:6671)
    at fk (react-dom.production.min.js:5648)
    at Zj (react-dom.production.min.js:5637)
    at Lj (react-dom.production.min.js:5393)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version 80.0.3987.163

**Comment by jaeger-j** [comment]
Hi @fran6co,

thank you for your contribution :-) 
It is already possible to deal with hierarchical labels to some extend. In order to do that you need to select all the subcategories you want to use when configuring an annotation task. 

See the picture below for an example. In order to select labels for annotation you need to click on a parent node. After that all the children will be selected as possible labels for the annotation task. In other words parent nodes are considered as a category of labels. For example if you want to use *mamals*, *plan* and *birds* as possible labels in the annotation tool, you need to click on their parent node *dummy tree*. If you also want to use *human*, *cat* and *cow*, you need to click on the *mamals* node (clicks are indicated by the red arrows and selected labels by red boxes).
 
<img width="447" alt="selecting_lbls" src="https://user-images.githubusercontent.com/37367934/81391091-ccd75f80-911c-11ea-9cf4-c83c38b8aae9.png">

The selected labels will now be available in the annotation tool. Please note that the labels will presented in flat style without hierarchy information  to the annotator. 
<img width="493" alt="selecting_lbls2" src="https://user-images.githubusercontent.com/37367934/81391110-d3fe6d80-911c-11ea-9a85-ee649b7356d4.png">

That SIA will crash when a not selected label is send to SIA is a bug and needs to be fixed.

Best,
Jonas

**Comment by fran6co** [comment]
That worked, it was a bit confusing
