### ISSUE TITLE
Making review step mandatory

### ISSUE THREAD

**Issue by Sagar1094** [l3p-cv/lost#94]
Hi,

First of all thanks for the amazing tool. 

I have created a custom pipeline which after completion of annotation task save data into a database. I just want to as one question, is it possible to make the review annotation step compulsory. I want to check the annotated images before saving them to database. I want the pipeline to wait for review annotation before executing export step. Thanks

**Comment by Sagar1094** [comment]
Hi, 
I have used a workaround for the review step, just one issue I am facing on a constant basis, would be great if you help me with the solution. When I review annotations the annotation tab keeps on getting timed out even when I am actively working on it. Due to which I have to start from the very starting everytime and can only go till 250 images out of my 900 odd images. Please help its important for a very important company project.

Thanks

**Comment by gereonreus** [comment]
Hello Sagar,

how did you realize your workaround ?

My suggestion would have been to connect a second annotation task behind the first one: To do so, there would have to be a separate script between the two Annotation Tasks, which reads the annotations from the first Annotation Task and requests them again. After the second Annotation Task, the export could then take place. 

If you use the Review option from the pipeline view (this option is only available since version 1.2.0), you have to scroll through the images from the very beginning.
It can happen that you get a session timeout if you have a large amount of images.
The time span for a session timeout can be set:
In the .env file (probably in the same folder where you run docker-compose up) you can overwrite the default time in minutes by adding the line "SESSION_TIMEOUT=30". You can set the number "30" to a value greater than 10. For example, a value of "120" would mean that the session would only expire after 2 hours. By default, the value is internally set to 30 minutes.

Please tell me the version of LOST you are using and a description of your workaround if my suggestions do not help you.

Best regards,
Gereon

**Comment by Sagar1094** [comment]
Hi,
My workaround is quite silly and simple 😅, I stopped at the last image and didn't finish the annotation task. I will do it once the review task is complete. Then annotate the last image and finish the task.

**Comment by Sagar1094** [comment]
Hi,
The version I am using is 1.0.0-alpha.4.
And I am not able to find the .env file. Could you please help me with this as well. Would be really grateful.

**Comment by Sagar1094** [comment]
Hi,
Have entered the above mentioned line in .env file and getting the error while executing docker-compose up:- 
File "/code/backend/lost/logic/config.py", line 29, in __init__
If self.session_timeout < 10
TypeError: '<' not supported between instances of 'str' and 'int' 
I believe any variable set in .env file is by default considered as str this is why it is happening and I dont know how to set it as int in .env file. However i tried changing config.py file of git cloned lost directory but it seems that docker is not referring to that file. I tried to find the file config.py which the docker-compose is referring bit unable to locate code folder. Could you let me know which config.py file is being referred here?

**Comment by Sagar1094** [comment]
Hi,
Suggested change in lost/logic/config.py line 28 :-
Self.session_timeout = int(os.environ["SESSION_TIMEOUT"]
As the value entered is taken as string by default the code giver error on line 29 as type error can not compare str with int
